### PR TITLE
Chat shortcode to output the chat anywhere.

### PR DESCRIPTION
**Pull request by elvismdev**
Wanted to contribute with this working shortcode to invoke a chat room from any custom location on template files or post or pages content. What do you think?

### CODE REVIEW

**Comment by royboy789** [comment]
Will test but merged for now. Thanks for making  keeping it clean.

**Comment by elvismdev** [comment]
You welcome. Using it from the template files with `<?php echo do_shortcode( '[ng-chatroom id="36"]' ); ?>` it works good. But when inserting the shortcode `[ng-chatroom id="36"]` in the content body of a page or post the chat room outputs wrapped inside this additional div `<div ng-app="wpAngularPlugin" class="ng-scope"> .... </div>` and this seems to conflict and mess up the functionality of the chat room loaded. Check my screenshot attached.

Any advise on how to output the chat without this additional div which mess up the things?

screen shot 2015-06-15 at 4 48 11 pm

**Comment by royboy789** [comment]
You need that wrapper 'cause that defines the AngularJS app to run the chatroom. Is it still functional or just a styling issue?

**Comment by royboy789** [comment]
I now understand the main issue. You need my AngularJS for WP plugin to run this plugin, however you can't have 2 AngularJS apps on a single page (well its not recommended). So shortcodes are kind of a pain because if you want to load any of the AngularJS for WP shortcodes on the same page, you can't because they are 2 different apps.

**Comment by royboy789** [comment]
Put in a fix into the angularjs for wp plugin to handle if chat shortcode is present.

**Comment by elvismdev** [comment]
Exactly, I understand also the conflict between the two apps, and realized that the conflicting code was being placed by the AngularJS plugin for WP. I was thinking about that exact fix you just made from the AngularJS plugin side. Will test it shortly, I'm sure it will handle now better this shortcode added into the content of pages and posts. Thankyou!

**Comment by royboy789** [comment]
These are the lines included in the AngularJS for WP plugin to help fix the shortcode issue with this plugin - https://github.com/royboy789/angularjs-for-wordpress/blob/master/includes/contentFilter.php#L11-L13

**Pull request merged**
